# --------------------------------------------------------
# X-Decoder -- Generalized Decoding for Pixel, Image, and Language
# Copyright (c) 2022 Microsoft
# Licensed under The MIT License [see LICENSE for details]
# Written by Xueyan Zou (xueyan@cs.wisc.edu)
# --------------------------------------------------------

##################
# Task settings
##################
WEIGHT: ''
PORT: 53711
VERBOSE: true
SAVE_DIR: '../../data/output/test'
MODEL:
  NAME: hoi_model
  HEAD: hoi_head
  MASK_ON: false
  KEYPOINT_ON: false
  LOAD_PROPOSALS: false
  DIM_PROJ: 512
  BACKBONE_DIM: 768
  BACKBONE:
    NAME: focal_dw
    PRETRAINED: ''
    LOAD_PRETRAINED: false
    FOCAL:
      PRETRAIN_IMG_SIZE: 224
      PATCH_SIZE: 4
      EMBED_DIM: 96
      DEPTHS: [2, 2, 6, 2]
      FOCAL_LEVELS: [3, 3, 3, 3]
      FOCAL_WINDOWS: [3, 3, 3, 3]
      DROP_PATH_RATE: 0.3
      MLP_RATIO: 4.0
      DROP_RATE: 0.0
      PATCH_NORM: True
      USE_CONV_EMBED: True
      SCALING_MODULATOR: True
      USE_CHECKPOINT: False
      USE_POSTLN: true
      USE_POSTLN_IN_MODULATION: false
      USE_LAYERSCALE: True
      OUT_FEATURES: ["res2", "res3", "res4", "res5"]
      OUT_INDICES: [0, 1, 2, 3]
  ENCODER:
    NAME: transformer_encoder_hoi
    IGNORE_VALUE: 255
    NUM_CLASSES: 133
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 512
    MASK_DIM: 512
    NORM: "GN"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ["res3", "res4", "res5"]
    COMMON_STRIDE: 4
    TRANSFORMER_ENC_LAYERS: 6
  DECODER:
    NAME: hdecoder
    MASK: False
    HIDDEN_DIM: 512
    NUM_OBJECT_QUERIES: 101
    NUM_OBJECT_CLASSES: 80
    NUM_VERB_CLASSES: 27
    NHEADS: 8
    DROPOUT: 0.1
    DIM_FEEDFORWARD: 2048
    PRE_NORM: False
    HOPD_DEC_LAYERS: 3
    INTERACTION_DEC_LAYERS: 3
    RETURN_INTERMEDIATE_DEC: False

    # matcher
    COST_OBJECT_CLASS: 1
    COST_VERB_CLASS: 1
    COST_BBOX: 1
    COST_GIOU: 1
    COST_MATCHING: 1

    # loss coefficients
    OBJ_LOSS_COEF: 1
    VERB_LOSS_COEF: 2
    BBOX_LOSS_COEF: 2.5
    GIOU_LOSS_COEF: 1
    MATCHING_LOSS_COEF: 1
    EOS_COEF: 0.1

INPUT:
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]

DATASETS:
  # open vocabulary segmentation evaluation.
  TRAIN: ["vcoco_train"]
  TEST: ["vcoco_val"]
  CLASS_CONCAT: false
  SIZE_DIVISIBILITY: 32
  PROPOSAL_FILES_TRAIN: []

DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 16
  LOAD_PROPOSALS: False
  SAMPLER_TRAIN: "TrainingSampler"
  ASPECT_RATIO_GROUPING: True

VCOCO:
  INPUT:
    MIN_SIZE_TEST: 512
    MAX_SIZE_TEST: 1024
    NUM_QUERIES: 100
    DATASET_MAPPER_NAME: "vcoco"
  DATALOADER:
    FILTER_EMPTY_ANNOTATIONS: False
    NUM_WORKERS: 0
    LOAD_PROPOSALS: False
    SAMPLER_TRAIN: "TrainingSampler"
    ASPECT_RATIO_GROUPING: False
  TEST:
    BATCH_SIZE_TOTAL: 8
  TRAIN:
    BATCH_SIZE_TOTAL: 2
    BATCH_SIZE_PER_GPU: 2